% Load the data generated by sacc_vs_luminance.sh runs
r = struct();
rr = [];

thetax=0
thetay=-10

plottraj = 0;
if plottraj
    num_runs=6 % to show
    figure(33);
    clf;
end

colours = {'r','b','g','k','c','m','r--','b--','g--','k--','c--','m--'};
colcount = 1;
% Search files in results directory and select all:
flist = glob('results/r*.dat');
llen = size(flist)(1);
for i = [1 : llen]

    rnm = flist{i};
    resdatname = substr(rnm, 9); % strips initial 'results/' string
    resdatname = substr(resdatname, 1, size(resdatname)(2)-4); % Strips '.dat' off
    resdatname = strrep (resdatname, '.', 'p');
    resdatname = strrep (resdatname, '-', 'm');

    %rnm = ['results/' resname];
    display(['Loading file ' rnm])
    load (rnm); % loads struct variable called result

    r = struct_merge (r, result);

    if (size(result.(resdatname))(2) == 12)
        rr = [rr; result.(resdatname)];
    end

    % Also plot each trajectory from the model run data
    if plottraj
        for j=1:num_runs
            filepath=['/fastdata/' getenv('USER') '/oculomotorRX0RY' num2str(thetay) '_' num2str(i) '_' num2str(j)];
            A=load_ocm_min(filepath);
            figure(33);
            hold on;
            plot (A.eyeRy, colours{colcount})
        end
    end
    colcount = colcount + 1;

end

% The rr array contains these columns:
% thetaX, thetaY, fix_lum, lumval, eyeRxAvg, eyeRyAvg, eyeRzAvg, eyeRxSD, eyeRySD, eyeRzSD, latmean, latsd
%
% sort rr on luminance value
rr = sortrows(rr,4);

figure(32);
% rr(:,3) is lumval
errorbar (rr(:,3),rr(:,5),rr(:,8),'o-')

% Achieved position (Rot X)
figure(32);
errorbar (rr(:,4),rr(:,5),rr(:,8),'o-')
xlabel('Luminance');
ylabel('eyeRx');

% Latency
figure(35);
errorbar (rr(:,4),rr(:,11),rr(:,12),'o-')
xlabel('Luminance');
ylabel('Latency (ms)');