% Load the data generated by sacc_vs_targetpos.sh runs for
% horizontal movements.
r = struct();
rrh = [];

lumval=1;

colours = {'r','b','g','k','c','m','r--','b--','g--','k--','c--','m--'};
colcount = 1;

modeldir = 'TModel4'

flist = glob(['results/' modeldir '_horz/r*.dat']);
llen = size(flist)(1);
for i = [1 : llen]

    rnm = flist{i};
    resdatname = substr(rnm, 14+length(modeldir)+1); % strips initial 'results' string
    resdatname = substr(resdatname, 1, size(resdatname)(2)-4); % Strips '.dat' off
    resdatname = strrep (resdatname, '.', 'p');
    resdatname = strrep (resdatname, '-', 'm');

    load (rnm); % loads struct variable called result
    r = struct_merge (r, result);

    % For expected size of rrh, consult sacc_vs_targetpos.m
    sz_2 = size(result.(resdatname))(2);

    if (sz_2 == 16)
        rrh = [rrh; result.(resdatname)];
    end

end

% The rrh array contains these columns:
% thetaX, thetaY, fix_lum, gap_ms, lumval, eyeRxAvg, eyeRyAvg, eyeRzAvg, eyeRxSD, eyeRySD, eyeRzSD, latmean, latsd, dopamine, durmean, dursd

%
% sort rrh on target position value
rrh = sortrows(rrh,2);

% Achieved position (Rot Y)
figure(62);
errorbar (rrh(:,2),rrh(:,7),rrh(:,10),'o-')
hold on;
plot ([-15,-7],[-15,-7], 'g--');
hold off;
xlabel('Target y');
ylabel('eyeRy');
legend(['Lum: ' num2str(rrh(1,5)) ' Dopa: ' num2str(rrh(1,14))])
title ('Horizontal');

% Latency
figure(65);
errorbar (rrh(:,2),rrh(:,12),rrh(:,13),'o-')
xlabel('Target y');
ylabel('Latency (ms)');
legend(['Lum: ' num2str(rrh(1,5)) ' Dopa: ' num2str(rrh(1,14))]);
title ('Horizontal');

% Duration
figure(66);
errorbar (rrh(:,2),rrh(:,15),rrh(:,16),'o-')
xlabel('Target y');
ylabel('Dur (ms)');
legend(['Lum: ' num2str(rrh(1,5)) ' Dopa: ' num2str(rrh(1,14))]);
ylim([80 160]);
title ('Horizontal');

% Duration shared fig
figure(100);
hold on;
errorbar (-rrh(:,2),rrh(:,15),rrh(:,16),'bo-')

% Output for Veusz
output_veusz = 0
if output_veusz
    targrot = [rrh(:,2),rrh(:,7),rrh(:,10)];
    f = fopen (['results/' modeldir '/sacc_eyery_vs_targ.csv'], 'w');
    fprintf (f, 'TargY,eyeRy,+-\n');
    dlmwrite (f, targrot, '-append');
    fclose(f);

    latrot = [rrh(:,2),rrh(:,12),rrh(:,13)];
    f = fopen (['results/' modeldir '/sacc_lat_vs_targ.csv'], 'w');
    fprintf (f, 'TargY,Latency,+-\n');
    dlmwrite (f, latrot, '-append');
    fclose(f);
end
