% Load the data generated by sacc_vs_targetpos.sh runs for
% horizontal movements.
r = struct();
rrv = [];

lumval=1;

colours = {'r','b','g','k','c','m','r--','b--','g--','k--','c--','m--'};
colcount = 1;

modeldir = 'TModel4'

flist = glob(['results/' modeldir '_vert/r*.dat']);
llen = size(flist)(1);
for i = [1 : llen]

    rnm = flist{i};
    resdatname = substr(rnm, 14+length(modeldir)+1); % strips initial 'results' string
    resdatname = substr(resdatname, 1, size(resdatname)(2)-4); % Strips '.dat' off
    resdatname = strrep (resdatname, '.', 'p');
    resdatname = strrep (resdatname, '-', 'm');

    load (rnm); % loads struct variable called result
    r = struct_merge (r, result);

    % For expected size of rrv, consult sacc_vs_targetpos.m
    sz_2 = size(result.(resdatname))(2);

    if (sz_2 == 16)
        rrv = [rrv; result.(resdatname)];
    end

end

% The rrv array contains these columns:
% thetaX, thetaY, fix_lum, gap_ms, lumval, eyeRxAvg, eyeRyAvg, eyeRzAvg, eyeRxSD, eyeRySD, eyeRzSD, latmean, latsd, dopamine, durmean, dursd

%
% sort rrv on target position value
rrv = sortrows(rrv,1);

% Achieved position (Rot X)
figure(72);
errorbar (rrv(:,1),rrv(:,6),rrv(:,9),'o-')
hold on;
plot ([-15,-7],[-15,-7], 'g--');
hold off;
xlabel('Target y');
ylabel('eyeRx');
legend(['Lum: ' num2str(rrv(1,5)) ' Dopa: ' num2str(rrv(1,14))])
title ('Vertical');

% Latency
figure(75);
errorbar (rrv(:,1),rrv(:,12),rrv(:,13),'o-')
xlabel('Target y');
ylabel('Latency (ms)');
legend(['Lum: ' num2str(rrv(1,5)) ' Dopa: ' num2str(rrv(1,14))]);
title ('Vertical');

% Duration
figure(76);
errorbar (rrv(:,1),rrv(:,15),rrv(:,16),'o-')
xlabel('Target y');
ylabel('Dur (ms)');
legend(['Lum: ' num2str(rrv(1,5)) ' Dopa: ' num2str(rrv(1,14))]);
ylim([80 160]);
title ('Vertical');

figure(100);
hold on;
errorbar (-rrv(:,1),rrv(:,15),rrv(:,16),'ko-')


% Output for Veusz
output_veusz = 0
if output_veusz
    targrot = [rrv(:,2),rrv(:,7),rrv(:,10)];
    f = fopen (['results/' modeldir '/sacc_eyery_vs_targ.csv'], 'w');
    fprintf (f, 'TargY,eyeRy,+-\n');
    dlmwrite (f, targrot, '-append');
    fclose(f);

    latrot = [rrv(:,2),rrv(:,12),rrv(:,13)];
    f = fopen (['results/' modeldir '/sacc_lat_vs_targ.csv'], 'w');
    fprintf (f, 'TargY,Latency,+-\n');
    dlmwrite (f, latrot, '-append');
    fclose(f);
end
