function rotations_report_vec (dbgfile, lastangle, eyeposAvg, eyeposSD, lasterror, error, reallylastweight, lastweight, weight, dedw)

    printf (['RR: last_angle: (%s) cur_angle: (%s) (sd %s)\n' ...
             'last_error: (%s) cur_error: (%s) last_weight: (%s)\n' ...
             'cur_weight: (%s) next_weight: (%s) dedw: (%s)\n'], ...
            num2str(lastangle),num2str(eyeposAvg), ...
            num2str(eyeposSD),num2str(lasterror),num2str(error), ...
            num2str(reallylastweight),num2str(lastweight), ...
            num2str(weight),num2str(dedw));

    fprintf (dbgfile, ['RR: last_angle: (%s) cur_angle: (%s) (sd %s)\n' ...
                       'last_error: (%s) cur_error: (%s) last_weight: (%s)\n' ...
                       'cur_weight: (%s) next_weight: (%s) dedw: (%s)\n'], ...
             num2str(lastangle),num2str(eyeposAvg), ...
             num2str(eyeposSD),num2str(lasterror),num2str(error), ...
             num2str(reallylastweight),num2str(lastweight), ...
             num2str(weight),num2str(dedw));
end
