function rotations_report (dbgfile, lastangle, eyeRyAvg, eyeRySD, lasterror, error, reallylastweight, lastweight, weight, dedw)

    printf (['RR: last_angle: %f cur_angle: %f (sd %f) last_error: %f cur_error: %f last_weight: %f ' ...
             'cur_weight: %f next_weight: %f dedw:' ...
             ' %f\n'], lastangle, eyeRyAvg, eyeRySD, lasterror, error, ...
            reallylastweight, lastweight, weight, dedw);

    fprintf (dbgfile, ['last_angle: %f cur_angle: %f (sd %f) last_error: %f cur_error: %f last_weight: %f ' ...
                       'cur_weight: %f next_weight: %f dedw:' ...
                       ' %f\n'], lastangle, eyeRyAvg, eyeRySD, lasterror, error, ...
             reallylastweight, lastweight, weight, dedw);
end
