function directories = setup_model_directories (targetTheta, counter, parcount)

    % Our output dir has to be on fastdata, because we submit the job
    % to run somewhere else and then on the node we submitted the
    % job from we'll consume the output, hence it has to be a
    % shared directory, even though /scratch may be faster.
    output_dir = ['/fastdata/co1ssj/oculomotorRX' ...
                  num2str(targetTheta(1)) 'RY' num2str(targetTheta(2)) ...
                  '_' num2str(counter)];
    % qlog dir has to be accessible from all nodes:
    qlog_dir = ['/fastdata/co1ssj/oculomotorRX' ...
                num2str(targetTheta(1)) 'RY' num2str(targetTheta(2)) ...
                '_' num2str(counter)];

    output_model_dir = [output_dir '/model'];
    output_run_dir = [output_dir '/run/'];
    output_log_dir = [output_dir '/log/'];

    directories = struct ('root', output_dir, ...
                          'qlog', qlog_dir, ...
                          'model', output_model_dir, ...
                          'run', output_run_dir, ...
                          'log', output_log_dir ...
    );

end
