% Load the data generated by sacc_vs_targetpos.sh runs for
% horizontal movements.
r = struct();
rr = [];

lumval=1;

colours = {'r','b','g','k','c','m','r--','b--','g--','k--','c--','m--'};
colcount = 1;

flist = glob('results/r*.dat');
llen = size(flist)(1);
for i = [1 : llen]

    rnm = flist{i};
    resdatname = substr(rnm, 9); % strips initial 'results' string
    resdatname = substr(resdatname, 1, size(resdatname)(2)-4); % Strips '.dat' off
    resdatname = strrep (resdatname, '.', 'p');
    resdatname = strrep (resdatname, '-', 'm');

    load (rnm); % loads struct variable called result
    r = struct_merge (r, result);

    % For expected size of rr, consult sacc_vs_targetpos.m
    sz_2 = size(result.(resdatname))(2);

    if (sz_2 == 14)
        rr = [rr; result.(resdatname)];
    end

end

% The rr array contains these columns:
% thetaX, thetaY, fix_lum, gap_ms, lumval, eyeRxAvg, eyeRyAvg, eyeRzAvg, eyeRxSD, eyeRySD, eyeRzSD, latmean, latsd, dopamine

%
% sort rr on target position value
rr = sortrows(rr,2);

% Achieved position (Rot Y)
figure(12);
errorbar (rr(:,2),rr(:,7),rr(:,10),'o-')
hold on;
plot ([-15,-8],[-15,-8], 'g--');
hold off;
xlabel('Target y');
ylabel('eyeRy');
legend(['Lum: ' num2str(rr(1,5)) ' Dopa: ' num2str(rr(1,14))])

% Latency
figure(15);
errorbar (rr(:,2),rr(:,12),rr(:,13),'o-')
xlabel('Target y');
ylabel('Latency (ms)');
legend(['Lum: ' num2str(rr(1,5)) ' Dopa: ' num2str(rr(1,14))]);

% Output for Veusz
targrot = [rr(:,2),rr(:,7),rr(:,10)];
f = fopen ('results/sacc_eyery_vs_targ.csv', 'w');
fprintf (f, 'TargY,eyeRy,+-\n');
dlmwrite (f, targrot, '-append');
fclose(f);

latrot = [rr(:,2),rr(:,12),rr(:,13)];
f = fopen ('results/sacc_lat_vs_targ.csv', 'w');
fprintf (f, 'TargY,Latency,+-\n');
dlmwrite (f, latrot, '-append');
fclose(f);
