% Load the data generated by sacc_vs_targetpos.sh runs for
% horizontal movements.
r = struct();
rr = [];
rr2 = [];

lumval=1;

colours = {'r','b','g','k','c','m','r--','b--','g--','k--','c--','m--'};
colcount = 1;

modeldir = 'TModel4'

flist = glob(['results/' modeldir '/r*.dat']);
llen = size(flist)(1);
for i = [1 : llen]

    rnm = flist{i};
    resdatname = substr(rnm, 9+length(modeldir)+1); % strips initial 'results' string
    resdatname = substr(resdatname, 1, size(resdatname)(2)-4); % Strips '.dat' off
    resdatname = strrep (resdatname, '.', 'p');
    resdatname = strrep (resdatname, '-', 'm');

    load (rnm); % loads struct variable called result
    r = struct_merge (r, result);

    % For expected size of rr, consult sacc_vs_targetpos.m
    sz_2 = size(result.(resdatname))(2);

    if (sz_2 >= 14)
        rr = [rr; result.(resdatname)(1:14)];
    end

end

% The rr array contains these columns:
% thetaX, thetaY, fix_lum, gap_ms, lumval, eyeRxAvg, eyeRyAvg, eyeRzAvg, eyeRxSD, eyeRySD, eyeRzSD, latmean, latsd, dopamine

%
% sort rr on target position value
rr = sortrows(rr,2);

rrr = struct();
for da = unique(rr(:,14))'
    da
    num2str(da)
    dname = ['da' num2str(da)];

    rrr.(dname) = rr(rr(:,14)==da,:);
end

% Achieved position (Rot Y)
figure(62);
errorbar (rr(:,2),rr(:,7),rr(:,10),'o-')
hold on;
plot ([-15,-7],[-15,-7], 'g--');
hold off;
xlabel('Target y');
ylabel('eyeRy');
legend(['Lum: ' num2str(rr(1,5)) ' Dopa: ' num2str(rr(1,14))])
title ('Horizontal');

% Latency
fs = 24;
figure(65); clf; hold on;
for da = unique(rr(:,14))'
    dname = ['da' num2str(da)];
    errorbar (-rrr.(dname)(:,2),rrr.(dname)(:,12),rrr.(dname)(:,13),'o-')
end
xlabel('Target eccentricity (deg)', 'fontsize', fs);
ylabel('Latency (ms)', 'fontsize', fs);
h_l = legend(['DA: ' num2str(rrr.('da0.3')(1,14))], ['DA: ' num2str(rrr.('da0.7')(1,14))], ['DA: ' num2str(rr3(1,14))]);
set (h_l, 'fontsize', fs)
title ('Horizontal', 'fontsize', fs);
set(gca, 'fontsize', fs);

% Output for Veusz
output_veusz = 1
if output_veusz
    targrot = [rr(:,2),rr(:,7),rr(:,10)];
    f = fopen (['results/' modeldir '/sacc_eyery_vs_targ.csv'], 'w');
    fprintf (f, 'TargY,eyeRy,+-\n');
    dlmwrite (f, targrot, '-append');
    fclose(f);

    latrot = [rr(:,2),rr(:,12),rr(:,13)];
    f = fopen (['results/' modeldir '/sacc_lat_vs_targ.csv'], 'w');
    fprintf (f, 'TargY,Latency,+-\n');
    dlmwrite (f, latrot, '-append');
    fclose(f);
end
